version: 1.0.{build}
configuration: Release
before_build:
- ps: nuget restore src -Verbosity quiet
build:
  verbosity: minimal
test:
  assemblies: '**\*.Tests.dll'
artifacts:
- path: 'bin\**\*.nupkg'
  name: NuGet package
