version: '{build}'
skip_tags: true
os: Visual Studio 2017
configuration: Release
environment:
  VisualStudioVersion: 15.0
before_build:
- ps: msbuild src\Xunit.StaFact.sln /nologo /m /v:quiet /t:restore
build_script:
- ps: msbuild src\Xunit.StaFact.sln /nologo /m /fl /v:quiet /t:build,pack
test:
  assemblies: '**\*.Tests.dll'
  categories:
    except:
    - FailureExpected
artifacts:
- path: 'bin\**\*.nupkg'
  name: NuGet package
