trigger:
  branches:
    include:
    - master
    - 'validate/*'
  paths:
    exclude:
    - doc/
    - '*.md'
    - .vscode/

variables:
  TreatWarningsAsErrors: true
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  BuildConfiguration: Release
  BuildPlatform: Any CPU
  ci_feed: 6ed146e5-8e9c-46d6-a40f-da9367ed50cd/c20edbb7-8403-4456-8f43-f46b47e360b1
  NUGET_PACKAGES: $(Agent.TempDirectory)/.nuget/packages

jobs:
- template: azure-pipelines/build.yml
