parameters:
- name: RunTests
- name: RunMacTests
  type: boolean
  default: false

steps:

- script: dotnet build -t:build,pack --no-restore -c $(BuildConfiguration) -warnAsError -warnNotAsError:NU1901,NU1902,NU1903,NU1904 /bl:"$(Build.ArtifactStagingDirectory)/build_logs/build.binlog"
  displayName: 🛠 dotnet build

- powershell: tools/dotnet-test-cloud.ps1 -Configuration $(BuildConfiguration) -Agent $(Agent.JobName) -PublishResults
  displayName: 🧪 dotnet test
  condition: and(succeeded(), ${{ parameters.RunTests }})

- ${{ if parameters.RunMacTests }}:
  - script: dotnet build --no-restore -c $(BuildConfiguration) ./test/Xunit.StaFact.Tests.Mac/Xunit.StaFact.Tests.Mac.csproj -t:Test -p:BuildProjectReferences=false
    displayName: 🧪 Mac-specific tests

  - task: PublishTestResults@2
    inputs:
      testResultsFormat: XUnit
      testResultsFiles: ./test_logs/Xunit.StaFact.Tests.Mac.xml
      testRunTitle: Xunit.StaFact.Tests.Mac (net8.0-macos, MacOS)
    displayName: 📢 Publish Mac-specific tests results
    condition: succeededOrFailed()
    continueOnError: true

- powershell: tools/variables/_define.ps1
  failOnStderr: true
  displayName: ⚙ Update pipeline variables based on build outputs
  condition: succeededOrFailed()

- powershell: azure-pipelines/publish_artifacts.ps1 -ArtifactNameSuffix "-$(Agent.JobName)" -Verbose
  failOnStderr: true
  displayName: 📢 Publish artifacts
  condition: succeededOrFailed()

- ${{ if and(ne(variables['codecov_token'], ''), parameters.RunTests) }}:
  - powershell: |
      $ArtifactStagingFolder = & "tools/Get-ArtifactsStagingDirectory.ps1"
      $CoverageResultsFolder = Join-Path $ArtifactStagingFolder "coverageResults-$(Agent.JobName)"
      tools/publish-CodeCov.ps1 -CodeCovToken "$(codecov_token)" -PathToCodeCoverage "$CoverageResultsFolder" -Name "$(Agent.JobName) Coverage Results" -Flags "$(Agent.JobName)"
    displayName: 📢 Publish code coverage results to codecov.io
    timeoutInMinutes: 3
    continueOnError: true
